apiVersion: v1
kind: Service
metadata:
  name: snake-game-service
  labels:
    app: snake-game
spec:
  type: NodePort
  selector:
    app: snake-game
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
